import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Platform } from 'react-native';

const generatePDF = async (measurement) => {
  const { heartRate, spO2, temperature, timestamp } = measurement;
  const date = new Date(timestamp.seconds * 1000).toLocaleString();

  const html = `
    <html>
      <head>
        <meta charset="utf-8" />
        <title>Measurement Report</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            background: #f7f7f7;
            color: #222;
            padding: 32px;
          }
          .container {
            background: #fff;
            border-radius: 12px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.08);
            max-width: 400px;
            margin: 0 auto;
            padding: 32px 24px;
          }
          h1 {
            color: #ff6347;
            text-align: center;
            margin-bottom: 32px;
            font-size: 2em;
          }
          .row {
            margin-bottom: 18px;
            font-size: 1.1em;
          }
          .label {
            font-weight: bold;
            color: #444;
          }
          .value {
            margin-left: 8px;
            color: #222;
          }
          .footer {
            margin-top: 32px;
            text-align: center;
            color: #888;
            font-size: 0.95em;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <h1>Measurement Report</h1>
          <div class="row"><span class="label">Heart Rate:</span><span class="value">${heartRate.toFixed(1)} bpm</span></div>
          <div class="row"><span class="label">SpO₂:</span><span class="value">${spO2.toFixed(1)} %</span></div>
          <div class="row"><span class="label">Temperature:</span><span class="value">${temperature.toFixed(1)} °C</span></div>
          <div class="row"><span class="label">Time:</span><span class="value">${date}</span></div>
          <div class="footer">Generated by Trackario</div>
        </div>
      </body>
    </html>
  `;

  const { uri } = await Print.printToFileAsync({ html });

  await Sharing.shareAsync(uri);

  return uri;
};

export default generatePDF;