import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    padding: 30, 
    backgroundColor: '#121212', 
    justifyContent: 'center',
    alignItems: 'center', 
  },
  label: {
    fontSize: 28, 
    fontWeight: 'bold',
    color: 'white',
    marginBottom: 30, 
    textAlign: 'center',
  },
  emergencyName: {
    fontSize: 22, 
    color: 'white',
    marginBottom: 15,
    textAlign: 'center', 
  },
  emergencyNumber: {
    fontSize: 22, 
    color: 'white',
    marginBottom: 40, 
    textAlign: 'center', 
  },
  button: {
    backgroundColor: 'tomato',
    paddingVertical: 8, 
    paddingHorizontal: 20, 
    borderRadius: 8, 
    alignSelf: 'center', 
  },
  buttonText: {
    color: 'white',
    fontSize: 16, 
    textAlign: 'center',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)', 
  },
  modalContent: {
    width: '90%', 
    backgroundColor: '#1e1e1e', 
    padding: 30, 
    borderRadius: 15, 
    alignItems: 'center',
  },
  modalLabel: {
    fontSize: 22, 
    color: 'white',
    marginBottom: 20,
    textAlign: 'center',
  },
  input: {
    height: 50, 
    borderColor: '#FF6347', 
    borderWidth: 1,
    paddingHorizontal: 15, 
    marginBottom: 25, 
    borderRadius: 8, 
    backgroundColor: '#2C2C2C', 
    color: 'white', 
    fontSize: 18, 
    width: '100%',
  },
  modalButton: {
    backgroundColor: 'tomato',
    paddingVertical: 8, 
    paddingHorizontal: 20, 
    borderRadius: 8, 
    alignItems: 'center',
    marginTop: 10, 
    width: '100%',
  },
});